### ISSUE TITLE
Migrate CML documentation to GitHub Pages

### ISSUE THREAD

**Issue by demianmnave** [demianmnave/CML1#10]
Ideas to investigate:

[Jekyll](http://jekyllrb.com/docs/home/)
[Moxygen](https://github.com/sourcey/moxygen)
[Pandoc](http://pandoc.org/)

Needs an [orphan branch](https://gist.github.com/seanbuscay/5877413).

**Comment by demianmnave** [comment]
Also consider:

[ReadTheDocs](https://read-the-docs.readthedocs.io/en/latest/index.html)

**Comment by demianmnave** [comment]
And:

http://madoko.org/reference.html

**Comment by demianmnave** [comment]
More Madoko:

https://github.com/sampsyo/madoko-template

**Comment by Brekel** [comment]
Or maybe at least an option to download the old html documentation pages, I really miss them at times for quick reference :)

**Comment by demianmnave** [comment]
I have a WordPress backup of the CML1 documentation, but punted for a while due to trouble getting it loaded onto a new server.  It's probably time to revisit that effort.

Running Doxygen on the CML1 headers _may_ get you a moderately useful reference until I figure out the WP import.  If you have switched to CML2, I was a little more careful with the Doxygen markup, so it may work a bit better.

**Comment by demianmnave** [comment]
Stroke of brilliance (aka obvious migration strategy) got old WordPress site up and running.  Makes this possible: 

http://www.adamwadeharris.com/how-to-convert-a-wordpress-site-to-jekyll-with-github-pages/

**Comment by demianmnave** [comment]
Kamino closed and cloned this issue to demianmnave/CML
