### ISSUE TITLE
Update CML2 to build against clang 3.6 and 3.7, as well as XCode 7.0

### ISSUE THREAD

**Issue by demianmnave** [demianmnave/CML1#6]
CML2 is not tested for XCode, but should at least be made to recognize clang 3.6 and 3.7, as well as XCode versions that match particular clang versions, starting with XCode 7.0.  The XCode CI support offered by [Travis CI](https://travis-ci.org/) may be a big help for this task.

- [x]  Build against clang 3.6 (also use Travis CI?)
- [x]  Build against clang 3.7 (also use Travis CI?)
- [x]  Setup Travis CI to build CML2 against XCode 7.3

Requested by: @Segmented
See also: #5

**Comment by demianmnave** [comment]
According to Travis CI, builds against XCode seem to be working as of version https://github.com/demianmnave/CML/commit/8dc407400f116a1a05f3bc2ff5b004592019dd2b.

@Segmented

**Comment by ghost** [comment]
Can confirm, it does seem to work now at least with my quick tests using clang on OSX, thanks! I don't use Xcode either so I cannot confirm that. I'm not sure how to run the unit tests for you, I tried `make test` and `cd tests; cmake .` to no avail. Currently `make install` does not seem to exist either; I simply copied the folder but I figure its worth noting.

**Comment by demianmnave** [comment]
Thanks for checking.  To configure testing you will need Boost installed. From the command line, start in your build directory and execute:

`cmake . -G<generator name> -DCML_BUILD_TESTING:Bool=On`

Then, to build the tests (again from your build directory):

`cmake --build . --config Release`

You can run the full test suite from your build directory by executing:

`ctest -C Release`

If you have multiple CPUs (e.g. 4 in this case), you can speed things up a bit using:

`ctest -C Release -j4`

I'll add this to the README also.

**Comment by demianmnave** [comment]
Kamino closed and cloned this issue to demianmnave/CML
